refactor: renamed whitelist option to allowList. this change still supports whitelist option
fastify/fastify-rate-limit pull request #117
Opened 2020-12-04 22:41 UTC by hidekysilva

#### Checklist

- [ x] run `npm run test` and `npm run benchmark`
- [ x] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-12-04 22:42 UTC, jsumners approved these changes
LGTM

2020-12-04 23:28 UTC, mcollina requested changes
Could you add back a test that verifies the `whitelist` alias?

2020-12-05 11:01 UTC, zekth requested changes

2020-12-05 11:01 UTC, zekth commented on index.d.ts
>    whitelist?: string[] | ((req: FastifyRequest, key: string) => boolean);
Please add:
```typescript
  /**
   * @deprecated Use `allowList` property
   */
```

2020-12-05 13:47 UTC, hidekysilva commented
I added the test which passed and the deprecated annotation. Now, one of the redis tests is failing even though it was passing before my last commit. Any suggestions?

2020-12-05 14:48 UTC, hidekysilva commented on index.d.ts
>    whitelist?: string[] | ((req: FastifyRequest, key: string) => boolean);
good to go

2020-12-05 16:10 UTC, Eomm approved these changes
+ other's suggestions

2020-12-05 18:14 UTC, zekth approved these changes
lgtm

2020-12-05 20:06 UTC, mcollina approved these changes
lgtm

2020-12-05 20:06 UTC, merged