feat(#191): Add another limiting strategy
fastify/fastify-rate-limit pull request #193
Opened 2021-12-09 22:42 UTC by vader-sama

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-12-10 05:36 UTC, climba03003 requested changes
It is actually forcing people to create more function in their custom store which should not be happen.

I think we can expose different official store for different strategy if they really need it.

2021-12-10 07:28 UTC, mcollina reviewed
good work!

2021-12-10 07:28 UTC, mcollina commented on test/global-rate-limit.test.js
> +  } catch (error) {
remove this try/catch

2021-12-10 07:28 UTC, mcollina commented on test/global-rate-limit.test.js
> +  } catch (error) {
remove the try/catch

2021-12-10 07:28 UTC, mcollina commented on test/route-rate-limit.test.js
> +  } catch (error) {
remove the try/catch

2021-12-10 07:28 UTC, mcollina commented on test/route-rate-limit.test.js
> +  } catch (error) {
remove the try/catch

2021-12-10 07:28 UTC, mcollina commented on test/route-rate-limit.test.js
> +  redis.quit(noop)
move these into a `t.teardown` function

2021-12-10 08:47 UTC, vader-sama commented
@climba03003 That's correct but they are coding a lot already (creating `incr` function), I think requested feature isn't in scope of this PR and It needs another PR; Don't you agree? 😉

2021-12-10 09:18 UTC, climba03003 commented
> @climba03003 That's correct but they are coding a lot already (creating `incr` function), I think requested feature isn't in scope of this PR and needs its own PR; Don't you agree? 😉

My suggest is preventing breaking change, it will break the people using `CustomStore` if they don't implement `incrAndRenew`. 


> @climba03003 That's correct but they are coding a lot already (creating `incr` function), I think requested feature isn't in scope of this PR and needs its own PR; Don't you agree? 😉

If we can provide a solution on `non-breaking-change`, I will go for that route. You can update the `storage` internal to provide the same feature.

I am against implementating one function for the store because it does not make sense on `CustomStore`.

2021-12-10 09:23 UTC, vader-sama commented
> > @climba03003 That's correct but they are coding a lot already (creating `incr` function), I think requested feature isn't in scope of this PR and needs its own PR; Don't you agree? 😉
> 
> If we can provide a solution on `non-breaking-change`, I will go for that route. You can update the `storage` internal to provide the same feature.
> 
> I am against implementating extra function for the store because it does not make sense on `CustomStore` use-case.

But what's the solution then?

2021-12-10 09:31 UTC, climba03003 commented
> 

After https://github.com/fastify/fastify-rate-limit/blob/master/index.js#L78, you can pass the option inside the store.
`pluginComponent.store.continueExceeding = params.continueExceeding` 
Then, just update `.incr` function in the two store we provide.

2021-12-10 09:34 UTC, climba03003 commented
Even better solution is that, update the `constructor` of the two `store` and accept new param.
Then, update the `.child` method that pass the `param`
Finally, update the `.incr` function.
If also allow us to `enable` this feature per route.

2021-12-10 09:51 UTC, vader-sama commented
@climba03003 What do you think now? (879ba4e57d2520)

2021-12-10 09:55 UTC, vader-sama commented
@climba03003 What do you think now? (17dbd486b)

2021-12-10 09:56 UTC, climba03003 approved these changes
LGTM. Thanks.

2021-12-10 13:50 UTC, mcollina approved these changes
lgtm

2021-12-11 19:40 UTC, vader-sama commented
@climba03003 Hi, this might be a weird question LOL; but is there any problem that my PR hasn't been merged yet?

2021-12-12 14:11 UTC, Eomm approved these changes

2021-12-12 14:11 UTC, merged