allow the user choose the namespace of the redis
fastify/fastify-rate-limit pull request #249
Opened 2022-07-15 23:17 UTC by DiogoMarques2003

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-07-16 07:44 UTC, mcollina requested changes

2022-07-16 07:44 UTC, mcollina commented on package.json
> +  "version": "7.1.1",
Please revert this, we'll bump when releasing.

2022-07-16 07:45 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2022-07-16 11:43 UTC, DiogoMarques2003 commented
> Thanks for opening a PR! Can you please add a unit test?

Unit teste for what ?

2022-07-16 15:13 UTC, Eomm commented
> Unit teste for what ?

That the redis key is what you expext

> I don't think it is necessary to add any more unit tests since it was only added an optional parameter in the options

In this way, we can't assure that this feature will be removed in future.

2022-07-16 16:42 UTC, DiogoMarques2003 commented
@Eomm is this ? Can you check pls

2022-07-16 17:03 UTC, Eomm approved these changes

2022-07-18 09:00 UTC, mcollina approved these changes
lgtm

2022-07-18 09:00 UTC, merged