Feature: allow function allowList and keyGenerator to be async/await
fastify/fastify-rate-limit pull request #256
Opened 2022-08-14 22:55 UTC by DiogoMarques2003

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-14 22:56 UTC, DiogoMarques2003 commented
I think isn't need add new unit test, but if is necessary pls tellme

2022-08-15 05:37 UTC, Uzlopak commented on index.d.ts
> +  async allowList?: string[] | ((req: FastifyRequest, key: string) => boolean);
```suggestion
  allowList?: string[] | ((req: FastifyRequest, key: string) => Promise<boolean>);
```

2022-08-15 05:37 UTC, Uzlopak commented on index.d.ts
> +  async keyGenerator?: (req: FastifyRequest) => string | number;
```suggestion
  keyGenerator?: (req: FastifyRequest) => string | number | Promise<string | number>;
```

2022-08-15 06:39 UTC, Uzlopak commented
It seems that your code is broken.

2022-08-15 07:42 UTC, Uzlopak commented on index.d.ts
> +  allowList?: string[] | ((req: FastifyRequest, key: string) => Promise<boolean>);
```suggestion
  allowList?: string[] | ((req: FastifyRequest, key: string) => boolean | Promise<boolean>);
```

2022-08-15 07:54 UTC, Uzlopak commented on index.js
> +  const hookHandler = await rateLimitRequestHandler(params, pluginComponent)
```suggestion
  const hookHandler = rateLimitRequestHandler(params, pluginComponent)
```

2022-08-15 07:54 UTC, Uzlopak commented on index.js
> +async function rateLimitRequestHandler (params, pluginComponent) {
```suggestion
function rateLimitRequestHandler (params, pluginComponent) {
```

2022-08-15 07:56 UTC, Uzlopak commented on index.js
> +function defaultOnBanReach (req, key) { }
```suggestion
function defaultOnBanReach (req, key) {}
```

2022-08-15 07:57 UTC, Uzlopak commented
@DiogoMarques2003 
Please provide some unit tests.

2022-08-15 09:06 UTC, mcollina requested changes
Those two functions are synchronous on purpuse.  Making them asynchronous and allowing I/O operations will defeat the purpose of this module.

2022-08-15 10:12 UTC, DiogoMarques2003 commented
But @mcollina i need consult the database in this functions, and the preValidation is executed after the ratelimit system

2022-08-15 10:24 UTC, Uzlopak commented
onRequestRateLimiter is already async. 

If you think that the await in front of the two potential async functions is a performance bottleneck, we could detect if one of those methods is async like this

```js
const asyncFunctionPrototype = Object.getPrototypeOf(async function() {});

function isAsyncFunction(v) {
  return (
    typeof v === 'function' &&
    Object.getPrototypeOf(v) === asyncFunctionPrototype
  );
};
```

and if so have a implementation were we have await and another one were we dont await. 

But again, onRequestRateLimiter is async.

2022-08-15 10:40 UTC, DiogoMarques2003 commented
@Uzlopak i need to do this on the allowList and keyGenerator functions:
![image](https://user-images.githubusercontent.com/52538977/184621065-cf1d7739-7fe3-452d-8798-6ceee0806144.png)
![image](https://user-images.githubusercontent.com/52538977/184621131-2925e297-533f-472e-bc74-a3f3bf35adfd.png)

can i do this databases requests in other place ?
I think no, and because of that it opens in this pull

2022-08-15 10:55 UTC, Uzlopak commented
I was answering mcollina

The only reason to reject this PR would be for me, when the performance decreases. And awaiting a non async function decreases the performance. So if the worry of mcollina is that we decrease the perf. by unnecessary awaiting then we can check if we either have an async function and then use it with await or sync methods and dont await. But this means some refactoring to avoid simply duplicating the current function.

2022-08-15 10:56 UTC, DiogoMarques2003 commented
oh ok ok

2022-08-15 13:25 UTC, Fdawgs commented
> The only reason to reject this PR would be for me, when the performance decreases. And awaiting a non async function decreases the performance.

Got any reading material around this @Uzlopak? Is it that is awaiting a sync function causes the returned value become a resolved Promise object, and the Promise causes overhead?

2022-08-15 13:38 UTC, Uzlopak commented
@Fdawgs 

I dont think that await wraps a sync method into a Promise.

I only had this issue once about 3 years ago: A sync function was awaited. When I removed the await from the sync-function the unit test became flaky. Investigating further, it revealed a very tight race condition in the sync-function. By awaiting the sync function it resulted in a short delay, which concealed the underlying race condition. I never investigated it further. 
I assume that await puts the result into the next run of the event loop, so the sync method was finished and did not show the race condition. But this is just an assumption.

2022-08-16 08:00 UTC, mcollina commented
The problem is not about promises but rather as a conscious design decision when implementing this module: providing some limited protection against API misuse and DoS attacks.

If we need to check against a _database_ to load some data, you are executing a database query before the check, and therefore you are likely vulnerable. In other terms: looking those things up from a database is counterproductive. This PR makes it _simpler_ to do something insecure and I'm not convinced we should support it.

---

You can achieve what you want by adding an `'onRequest'` hook before registering this module. In the `'onRequest'` hook, you should add those values to the request object. __I do not recommend this__.

2022-08-16 08:05 UTC, DiogoMarques2003 commented
> The problem is not about promises but rather as a conscious design decision when implementing this module: providing some limited protection against API misuse and DoS attacks.
> 
> If we need to check against a _database_ to load some data, you are executing a database query before the check, and therefore you are likely vulnerable. In other terms: looking those things up from a database is counterproductive. This PR makes it _simpler_ to do something insecure and I'm not convinced we should support it.
> 
> You can achieve what you want by adding an `'onRequest'` hook before registering this module. In the `'onRequest'` hook, you should add those values to the request object. **I do not recommend this**.

Can you show an example to add the database requests in `'onRequest'` to be executed before calling the rate limit ?

2022-08-16 08:08 UTC, mcollina commented
Something like this should work

```js
app.addHook('onRequest', async (req) => {
  // Don't do this, it's very unsafe
  const { id, allowList } = await callMyDb()
  req.aLongPropertyName = id
  req.aLongPropertyName2 = allowList
})
fastify.register(require('@fastify/rate-limit'), ...)
```

2022-08-16 17:41 UTC, DiogoMarques2003 commented
> The problem is not about promises but rather as a conscious design decision when implementing this module: providing some limited protection against API misuse and DoS attacks.
> 
> If we need to check against a _database_ to load some data, you are executing a database query before the check, and therefore you are likely vulnerable. In other terms: looking those things up from a database is counterproductive. This PR makes it _simpler_ to do something insecure and I'm not convinced we should support it.
> 
> You can achieve what you want by adding an `'onRequest'` hook before registering this module. In the `'onRequest'` hook, you should add those values to the request object. **I do not recommend this**.

The max function is async, so maybe can also be

2022-08-16 18:29 UTC, mcollina commented
Ok, I'm sold. Let's make this possible.

2022-08-16 18:32 UTC, Uzlopak commented
lol, I will give the approval so that you dont have to :D

2022-08-16 18:32 UTC, Uzlopak approved these changes

2022-08-17 05:38 UTC, Eomm requested changes
> I think isn't need add new unit test, but if is necessary pls tellme

Without a test we can't assure this feature will be removed accidentally from other PRs.

Please, add 2 tests (happy path and error case) for each change

2022-08-17 17:46 UTC, DiogoMarques2003 commented
![image](https://user-images.githubusercontent.com/52538977/185207222-6b35db22-4c37-458b-9ad8-55b526fb4a9a.png)

@Eomm In my pc the all tests pass, why here in github don't pass ?

2022-08-18 08:02 UTC, Uzlopak commented
Your tests fail in the CI pipeline.

2022-08-18 17:09 UTC, DiogoMarques2003 commented
> Your tests fail in the CI pipeline.

What should I do ?

2022-08-18 17:14 UTC, Eomm commented
Could you try to rebase the branch?

```
git rebase upstream/master
```

2022-08-18 17:25 UTC, Uzlopak commented
I rerun the workflow, but it seems that the tests are now flaky with the additional awaits.

2022-08-18 17:46 UTC, DiogoMarques2003 commented
> Reference in ne

this is strange because on my computer they all ran correctly

2022-08-18 17:55 UTC, DiogoMarques2003 commented
![image](https://user-images.githubusercontent.com/52538977/185462305-0e86a15c-bb4e-423e-b65b-87e0de0320cc.png)

this is very stranger

2022-08-18 20:21 UTC, Eomm commented
> > Reference in ne
> 
> this is strange because on my computer they all ran correctly

It may depend on the node.js version.

Here are the logs of the run:
https://github.com/fastify/fastify-rate-limit/runs/7904283030?check_suite_focus=true

It seems that the namespace test is always failing.

2022-08-18 20:30 UTC, DiogoMarques2003 commented
> > > Reference in ne
> > 
> > 
> > this is strange because on my computer they all ran correctly
> 
> It may depend on the node.js version.
> 
> Here are the logs of the run: https://github.com/fastify/fastify-rate-limit/runs/7904283030?check_suite_focus=true
> 
> It seems that the namespace test is always failing.

Maybe, i'm using version 16.6.0

2022-09-13 15:00 UTC, DiogoMarques2003 commented
@Eomm any soluction for this ?

2022-09-13 19:22 UTC, DiogoMarques2003 commented
> 

for some reason myFunction.constructor.name don't exists

2022-09-13 19:35 UTC, Eomm commented
it was a code example, you need to use your own function `keyGenerator` and `allowList`

2022-09-13 19:39 UTC, DiogoMarques2003 commented
> it was a code example, you need to use your own function `keyGenerator` and `allowList`

yes, i do this but don't work in  any test 
![image](https://user-images.githubusercontent.com/52538977/189994115-1c252600-49d4-4a77-b85c-4626f4f4d41f.png)

2022-09-14 06:38 UTC, Eomm commented
Should not it be `params.allowList?.constructor.name`?

2022-09-14 07:36 UTC, Uzlopak commented
@Eomm 
Its a race condition. PR incoming

2022-09-14 07:49 UTC, Uzlopak commented
#261 fixes the issues.

2022-09-14 12:15 UTC, Uzlopak commented
You can actually use a prototype check

```js
const asyncFunctionPrototype = Object.getPrototypeOf(async function() {})

function isAsyncFunction(v) {
    return (
      typeof v === 'function' &&
      Object.getPrototypeOf(v) === asyncFunctionPrototype
    )
  }
```

2022-09-30 20:08 UTC, Uzlopak commented
@Eomm 
What needs to be done to get this PR merged?

2022-10-01 07:30 UTC, Eomm commented
- a quick doc note
- the isAsyncFunction check

2022-10-03 05:41 UTC, Eomm approved these changes

2022-10-04 09:29 UTC, Uzlopak commented
@Eomm 
The isAsyncFunction-check is not added. I think adding that would be maybe not that smart, as a sync function returning a promise would not be detected.

2022-10-04 15:17 UTC, Eomm commented
I'm ok landing it, there is a blocking review from @mcollina

2022-10-06 22:57 UTC, Uzlopak commented
@mcollina 

PTAL

2022-10-09 16:47 UTC, mcollina approved these changes
lgtm

2022-10-09 18:10 UTC, merged