fix: remove unnecessary parameter timeWindow
fastify/fastify-rate-limit pull request #363
Opened 2024-02-22 13:22 UTC by gurgunday

We no longer need to have a `timeWindow` property since it will be passed dynamically to the `incr` method

2024-02-22 13:28 UTC, gurgunday commented
Note: this change won't affect custom stores since to them we pass all the options anyway

2024-02-23 10:15 UTC, mcollina requested changes
Can you update the docs?

2024-02-23 10:24 UTC, gurgunday commented
Here: https://github.com/fastify/fastify-rate-limit/pull/360

2024-02-23 11:11 UTC, mcollina approved these changes
lgtm

2024-02-23 11:16 UTC, merged