Add function to manually check rate limit (#346)
fastify/fastify-rate-limit pull request #392
Opened 2024-11-10 20:12 UTC by Charioteer

Hey fastify contributors,

Following on from issue #346 and my [comment](https://github.com/fastify/fastify-rate-limit/issues/346#issuecomment-2331639190), I finally had some spare time to implement a draft version of my idea as suggested by @mcollina. I realized that any store (child) instance receives all the `options` provided to `fastify.rateLimit` when it is constructed, which is why I had to adjust my initial idea and come up with a slightly different solution.

I did not provide any documentation or additional tests yet (all existing tests run green tho), because I wanted to ask for your feedback first.

Please let me know what you think and as soon as everything looks good to you, I will finalize my PR with proper docs and tests.

Thanks and cheers
Patrick

# How to Use

```ts
import Fastify from "fastify";
import { fastifyRateLimit } from "@fastify/rate-limit";

const fastify = Fastify();

await fastify.register(fastifyRateLimit, {
  global: false,
  max: 10,
  timeWindow: "10 seconds",
});

const checkRateLimit = fastify.createRateLimit(); // this will use the global options provided to fastifyRateLimit

fastify.get("/", async (request, reply) => {
  const limit = await checkRateLimit(request);

  if(!limit.isAllowed && limit.isExceeded) {
    return reply.code(429).send("Limit exceeded");
  }

  return reply.send("Hello world");
});

const checkCustomRateLimit = fastify.createRateLimit({ max: 100 }); // max provided to override global options

fastify.get("/custom", async (request, reply) => {
  const limit = await checkCustomRateLimit(request);

  if(!limit.isAllowed && limit.isExceeded) {
    return reply.code(429).send("Limit exceeded");
  }

  return reply.send("Hello world");
});
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-12-07 02:48 UTC, mcollina reviewed
Looks good! Finish it up (be careful that CI is failing).

2025-02-03 22:10 UTC, Charioteer commented
Hi @mcollina,

after @umakantp has closed their PR #410 because of the "authorship problem", I thought of putting more pressure on myself to finally get this done. I added unit tests, type tests, as well as documentation about the usage of this feature. I also merged the latest commit of `fastify-rate-limit` to my fork already to avoid conflicts. LMKWYT.

At this point, I also would like to appreciate @umakantp again for continuing this PR and putting time and effort into it. Please excuse me if I caused any trouble on your side.

2025-02-14 04:01 UTC, umakantp commented
Hi @mcollina If you can please take a look and merge if things are good?

2025-03-12 01:15 UTC, gurgunday commented
It looks interesting, I'll take a look at this tomorrow

2025-03-15 06:39 UTC, Eomm reviewed
Technically this change is awesome!

A minor suggestion, but LGTM!

2025-03-15 06:39 UTC, Eomm commented on index.js
> +      return (req) => applyRateLimit(...args, req)
Instead of decostruct `args` we can:
```suggestion
      return (req) => applyRateLimit.apply(this, args.concat(req))
```

(and even better, avoid the `concat`

2025-03-15 20:59 UTC, gurgunday reviewed
Can you run a benchmark using the basic example in the examples folder with `autocannon`?

https://github.com/fastify/fastify-rate-limit/blob/main/example/example-simple.mjs

2025-04-17 15:40 UTC, Charioteer commented
Hi @gurgunday,

sorry for yet anoter late reply...

I wasn't sure which kind of benchmarks you'd expect. I still ran two benchmarks with `autocannon` and its default settings on my machine with my initial version **without** @Eomm's suggestion:
```
Running 10s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 1 ms  │ 1 ms │ 0.05 ms │ 0.29 ms │ 16 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg       │ Stdev    │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Req/Sec   │ 14,959  │ 14,959  │ 18,431  │ 19,039  │ 18,150.91 │ 1,103.65 │ 14,959  │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Bytes/Sec │ 4.42 MB │ 4.42 MB │ 6.95 MB │ 7.18 MB │ 6.73 MB   │ 751 kB   │ 4.42 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 11

10000 2xx responses, 189656 non 2xx responses
200k requests in 11.02s, 74 MB read
```

and with @Eomm's suggestion:
```
Running 10s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 1 ms  │ 1 ms │ 0.05 ms │ 0.24 ms │ 18 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬───────────┬────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg       │ Stdev  │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼────────┼─────────┤
│ Req/Sec   │ 15,791  │ 15,791  │ 18,399  │ 19,247  │ 18,348.73 │ 897.8  │ 15,785  │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼────────┼─────────┤
│ Bytes/Sec │ 4.73 MB │ 4.73 MB │ 6.93 MB │ 7.25 MB │ 6.81 MB   │ 673 kB │ 4.73 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴───────────┴────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 11

10000 2xx responses, 191806 non 2xx responses
202k requests in 11.02s, 74.9 MB read
```

## Machine and Versions
- Machine (MacBook Pro 2019): 
  - CPU: 2,3 GHz 8-Core Intel Core i9
  - GPU: AMD Radeon Pro 5500M 4 GB
  - RAM: 16 GB 2667 MHz DDR4
  - OS: Sonoma 14.5
- Node v22.14.0
- Fastify 5.3.0

2025-05-06 06:37 UTC, umakantp commented
Looks like this has fallen behind on the priority list? @gurgunday ?

2025-05-07 19:08 UTC, gurgunday commented
Hey, sorry for the late reply, just to get an idea, can you run the same on `master` too? I will approve if there isn't a huge regression

2025-05-08 22:00 UTC, Charioteer commented
Hey @gurgunday,

I ran the benchmark again for `main@latest` and for my PR in sequence so that the comparison is as fair as possible. System and versions did not change.

## Master
```
Running 10s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 1 ms  │ 1 ms │ 0.05 ms │ 0.32 ms │ 22 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg       │ Stdev    │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Req/Sec   │ 14,175  │ 14,175  │ 19,119  │ 19,423  │ 18,633.82 │ 1,436.04 │ 14,174  │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Bytes/Sec │ 4.12 MB │ 4.12 MB │ 7.21 MB │ 7.32 MB │ 6.91 MB   │ 888 kB   │ 4.12 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 11

10000 2xx responses, 194989 non 2xx responses
205k requests in 11.02s, 76.1 MB read
```

## My PR
```
Running 10s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 1 ms  │ 1 ms │ 0.05 ms │ 0.32 ms │ 23 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg       │ Stdev    │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Req/Sec   │ 15,399  │ 15,399  │ 18,159  │ 19,151  │ 18,119.64 │ 1,019.03 │ 15,392  │
├───────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┤
│ Bytes/Sec │ 4.58 MB │ 4.58 MB │ 6.85 MB │ 7.22 MB │ 6.72 MB   │ 707 kB   │ 4.58 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 11

10000 2xx responses, 189305 non 2xx responses
199k requests in 11.02s, 73.9 MB read
```

## TL;DR
My PR has about <ins>**2.9%** less throughput</ins>. Let me know if that is too much regression. I did not check whether there is room for improvement yet.

2025-05-09 11:02 UTC, gurgunday approved these changes
I think 2% is acceptable, we should be able to improve this further with some optimizations but it lgtm currently for this PR

2025-05-09 11:38 UTC, Fdawgs requested changes
Blocking until I can find time to review, from brief glance the docs could be refined.

2025-05-12 17:48 UTC, Fdawgs commented on README.md
> +The next example demonstrates the usage of a custom rate limiter:
```suggestion
A custom limiter function can be created with `fastify.createRateLimit()`, which is handy when needing to integrate with
technologies like [GraphQL](https://graphql.org/) or [tRPC](https://trpc.io/). This function uses the global [options](#options) set
during plugin registration, but you can override options such as `store`, `skipOnError`, `max`, `timeWindow`,
`allowList`, `keyGenerator`, and `ban`.

Example usage:
```

2025-05-12 17:48 UTC, Fdawgs commented on README.md
> +```ts
```suggestion
```js
```

2025-05-13 17:34 UTC, Fdawgs approved these changes

2025-05-14 09:42 UTC, Eomm commented on README.md
> +  max: 100,
without it, routes will have 2 rate limit hooks

```suggestion
  global : false,
  max: 100,
```

2025-05-14 09:42 UTC, Eomm commented on README.md
> + // checkRateLimit will use the global options provided above when called
```suggestion
// checkRateLimit will use the global options provided above when called
```

2025-05-14 09:42 UTC, Eomm commented on index.js
> +      return rateLimitRequestHandler(...args)
```suggestion
      return rateLimitRequestHandler.apply(this, args)
```

2025-05-16 12:41 UTC, Fdawgs commented on index.js
> +      return rateLimitRequestHandler(...args)
Enlighten me @Eomm, is apply faster than the spread?

2025-05-17 12:53 UTC, Eomm commented on index.js
> +      return rateLimitRequestHandler(...args)
It was not for perf, but for the `this` context - but yeah, rechecked it and we don't need it!

2025-05-18 07:16 UTC, Eomm approved these changes

2025-05-18 07:16 UTC, merged